--- Altered from http://www.mediacollege.com/internet/samples/html/country-list.html

INSERT INTO country(code, name) VALUES ('AF','Afghanistan');
INSERT INTO country(code, name) VALUES ('AL','Albania');
INSERT INTO country(code, name) VALUES ('DZ','Algeria');
INSERT INTO country(code, name) VALUES ('AS','American Samoa');
INSERT INTO country(code, name) VALUES ('AD','Andorra');
INSERT INTO country(code, name) VALUES ('AO','Angola');
INSERT INTO country(code, name) VALUES ('AI','Anguilla');
INSERT INTO country(code, name) VALUES ('AG','Antigua & Barbuda');
INSERT INTO country(code, name) VALUES ('AR','Argentina');
INSERT INTO country(code, name) VALUES ('AA','Armenia');
INSERT INTO country(code, name) VALUES ('AW','Aruba');
INSERT INTO country(code, name) VALUES ('AU','Australia');
INSERT INTO country(code, name) VALUES ('AT','Austria');
INSERT INTO country(code, name) VALUES ('AZ','Azerbaijan');
INSERT INTO country(code, name) VALUES ('BS','Bahamas');
INSERT INTO country(code, name) VALUES ('BH','Bahrain');
INSERT INTO country(code, name) VALUES ('BD','Bangladesh');
INSERT INTO country(code, name) VALUES ('BB','Barbados');
INSERT INTO country(code, name) VALUES ('BY','Belarus');
INSERT INTO country(code, name) VALUES ('BE','Belgium');
INSERT INTO country(code, name) VALUES ('BZ','Belize');
INSERT INTO country(code, name) VALUES ('BJ','Benin');
INSERT INTO country(code, name) VALUES ('BM','Bermuda');
INSERT INTO country(code, name) VALUES ('BT','Bhutan');
INSERT INTO country(code, name) VALUES ('BO','Bolivia');
INSERT INTO country(code, name) VALUES ('BL','Bonaire');
INSERT INTO country(code, name) VALUES ('BA','Bosnia & Herzegovina');
INSERT INTO country(code, name) VALUES ('BW','Botswana');
INSERT INTO country(code, name) VALUES ('BR','Brazil');
INSERT INTO country(code, name) VALUES ('BC','British Indian Ocean Ter');
INSERT INTO country(code, name) VALUES ('BN','Brunei');
INSERT INTO country(code, name) VALUES ('BG','Bulgaria');
INSERT INTO country(code, name) VALUES ('BF','Burkina Faso');
INSERT INTO country(code, name) VALUES ('BI','Burundi');
INSERT INTO country(code, name) VALUES ('KH','Cambodia');
INSERT INTO country(code, name) VALUES ('CM','Cameroon');
INSERT INTO country(code, name) VALUES ('CA','Canada');
INSERT INTO country(code, name) VALUES ('IC','Canary Islands');
INSERT INTO country(code, name) VALUES ('CV','Cape Verde');
INSERT INTO country(code, name) VALUES ('KY','Cayman Islands');
INSERT INTO country(code, name) VALUES ('CF','Central African Republic');
INSERT INTO country(code, name) VALUES ('TD','Chad');
INSERT INTO country(code, name) VALUES ('CD','Channel Islands');
INSERT INTO country(code, name) VALUES ('CL','Chile');
INSERT INTO country(code, name) VALUES ('CN','China');
INSERT INTO country(code, name) VALUES ('CI','Christmas Island');
INSERT INTO country(code, name) VALUES ('CS','Cocos Island');
INSERT INTO country(code, name) VALUES ('CO','Colombia');
INSERT INTO country(code, name) VALUES ('CC','Comoros');
INSERT INTO country(code, name) VALUES ('CG','Congo');
INSERT INTO country(code, name) VALUES ('CK','Cook Islands');
INSERT INTO country(code, name) VALUES ('CR','Costa Rica');
INSERT INTO country(code, name) VALUES ('CT','Cote D\'Ivoire');
INSERT INTO country(code, name) VALUES ('HR','Croatia');
INSERT INTO country(code, name) VALUES ('CU','Cuba');
INSERT INTO country(code, name) VALUES ('CB','Curacao');
INSERT INTO country(code, name) VALUES ('CY','Cyprus');
INSERT INTO country(code, name) VALUES ('CZ','Czech Republic');
INSERT INTO country(code, name) VALUES ('DK','Denmark');
INSERT INTO country(code, name) VALUES ('DJ','Djibouti');
INSERT INTO country(code, name) VALUES ('DM','Dominica');
INSERT INTO country(code, name) VALUES ('DO','Dominican Republic');
INSERT INTO country(code, name) VALUES ('TM','East Timor');
INSERT INTO country(code, name) VALUES ('EC','Ecuador');
INSERT INTO country(code, name) VALUES ('EG','Egypt');
INSERT INTO country(code, name) VALUES ('SV','El Salvador');
INSERT INTO country(code, name) VALUES ('GQ','Equatorial Guinea');
INSERT INTO country(code, name) VALUES ('ER','Eritrea');
INSERT INTO country(code, name) VALUES ('EE','Estonia');
INSERT INTO country(code, name) VALUES ('ET','Ethiopia');
INSERT INTO country(code, name) VALUES ('FA','Falkland Islands');
INSERT INTO country(code, name) VALUES ('FO','Faroe Islands');
INSERT INTO country(code, name) VALUES ('FJ','Fiji');
INSERT INTO country(code, name) VALUES ('FI','Finland');
INSERT INTO country(code, name) VALUES ('FR','France');
INSERT INTO country(code, name) VALUES ('GF','French Guiana');
INSERT INTO country(code, name) VALUES ('PF','French Polynesia');
INSERT INTO country(code, name) VALUES ('FS','French Southern Ter');
INSERT INTO country(code, name) VALUES ('GA','Gabon');
INSERT INTO country(code, name) VALUES ('GM','Gambia');
INSERT INTO country(code, name) VALUES ('GE','Georgia');
INSERT INTO country(code, name) VALUES ('DE','Germany');
INSERT INTO country(code, name) VALUES ('GH','Ghana');
INSERT INTO country(code, name) VALUES ('GI','Gibraltar');
INSERT INTO country(code, name) VALUES ('GR','Greece');
INSERT INTO country(code, name) VALUES ('GL','Greenland');
INSERT INTO country(code, name) VALUES ('GD','Grenada');
INSERT INTO country(code, name) VALUES ('GP','Guadeloupe');
INSERT INTO country(code, name) VALUES ('GU','Guam');
INSERT INTO country(code, name) VALUES ('GT','Guatemala');
INSERT INTO country(code, name) VALUES ('GN','Guinea');
INSERT INTO country(code, name) VALUES ('GY','Guyana');
INSERT INTO country(code, name) VALUES ('HT','Haiti');
INSERT INTO country(code, name) VALUES ('HW','Hawaii');
INSERT INTO country(code, name) VALUES ('HN','Honduras');
INSERT INTO country(code, name) VALUES ('HK','Hong Kong');
INSERT INTO country(code, name) VALUES ('HU','Hungary');
INSERT INTO country(code, name) VALUES ('IS','Iceland');
INSERT INTO country(code, name) VALUES ('IN','India');
INSERT INTO country(code, name) VALUES ('ID','Indonesia');
INSERT INTO country(code, name) VALUES ('IA','Iran');
INSERT INTO country(code, name) VALUES ('IQ','Iraq');
INSERT INTO country(code, name) VALUES ('IR','Ireland');
INSERT INTO country(code, name) VALUES ('IM','Isle of Man');
INSERT INTO country(code, name) VALUES ('IL','Israel');
INSERT INTO country(code, name) VALUES ('IT','Italy');
INSERT INTO country(code, name) VALUES ('JM','Jamaica');
INSERT INTO country(code, name) VALUES ('JP','Japan');
INSERT INTO country(code, name) VALUES ('JO','Jordan');
INSERT INTO country(code, name) VALUES ('KZ','Kazakhstan');
INSERT INTO country(code, name) VALUES ('KE','Kenya');
INSERT INTO country(code, name) VALUES ('KI','Kiribati');
INSERT INTO country(code, name) VALUES ('NK','Korea North');
INSERT INTO country(code, name) VALUES ('KS','Korea South');
INSERT INTO country(code, name) VALUES ('KW','Kuwait');
INSERT INTO country(code, name) VALUES ('KG','Kyrgyzstan');
INSERT INTO country(code, name) VALUES ('LA','Laos');
INSERT INTO country(code, name) VALUES ('LV','Latvia');
INSERT INTO country(code, name) VALUES ('LB','Lebanon');
INSERT INTO country(code, name) VALUES ('LS','Lesotho');
INSERT INTO country(code, name) VALUES ('LR','Liberia');
INSERT INTO country(code, name) VALUES ('LY','Libya');
INSERT INTO country(code, name) VALUES ('LI','Liechtenstein');
INSERT INTO country(code, name) VALUES ('LT','Lithuania');
INSERT INTO country(code, name) VALUES ('LU','Luxembourg');
INSERT INTO country(code, name) VALUES ('MO','Macau');
INSERT INTO country(code, name) VALUES ('MK','Macedonia');
INSERT INTO country(code, name) VALUES ('MG','Madagascar');
INSERT INTO country(code, name) VALUES ('MY','Malaysia');
INSERT INTO country(code, name) VALUES ('MW','Malawi');
INSERT INTO country(code, name) VALUES ('MV','Maldives');
INSERT INTO country(code, name) VALUES ('ML','Mali');
INSERT INTO country(code, name) VALUES ('MT','Malta');
INSERT INTO country(code, name) VALUES ('MH','Marshall Islands');
INSERT INTO country(code, name) VALUES ('MQ','Martinique');
INSERT INTO country(code, name) VALUES ('MR','Mauritania');
INSERT INTO country(code, name) VALUES ('MU','Mauritius');
INSERT INTO country(code, name) VALUES ('YT','Mayotte');
INSERT INTO country(code, name) VALUES ('MX','Mexico');
INSERT INTO country(code, name) VALUES ('MI','Midway Islands');
INSERT INTO country(code, name) VALUES ('MD','Moldova');
INSERT INTO country(code, name) VALUES ('MC','Monaco');
INSERT INTO country(code, name) VALUES ('MN','Mongolia');
INSERT INTO country(code, name) VALUES ('MS','Montserrat');
INSERT INTO country(code, name) VALUES ('MA','Morocco');
INSERT INTO country(code, name) VALUES ('MZ','Mozambique');
INSERT INTO country(code, name) VALUES ('MM','Myanmar');
INSERT INTO country(code, name) VALUES ('NA','Nambia');
INSERT INTO country(code, name) VALUES ('NU','Nauru');
INSERT INTO country(code, name) VALUES ('NP','Nepal');
INSERT INTO country(code, name) VALUES ('AN','Netherland Antilles');
INSERT INTO country(code, name) VALUES ('NL','Netherlands (Holland, Europe)');
INSERT INTO country(code, name) VALUES ('NV','Nevis');
INSERT INTO country(code, name) VALUES ('NC','New Caledonia');
INSERT INTO country(code, name) VALUES ('NZ','New Zealand');
INSERT INTO country(code, name) VALUES ('NI','Nicaragua');
INSERT INTO country(code, name) VALUES ('NE','Niger');
INSERT INTO country(code, name) VALUES ('NG','Nigeria');
INSERT INTO country(code, name) VALUES ('NW','Niue');
INSERT INTO country(code, name) VALUES ('NF','Norfolk Island');
INSERT INTO country(code, name) VALUES ('NO','Norway');
INSERT INTO country(code, name) VALUES ('OM','Oman');
INSERT INTO country(code, name) VALUES ('PK','Pakistan');
INSERT INTO country(code, name) VALUES ('PW','Palau Island');
INSERT INTO country(code, name) VALUES ('PS','Palestine');
INSERT INTO country(code, name) VALUES ('PA','Panama');
INSERT INTO country(code, name) VALUES ('PG','Papua New Guinea');
INSERT INTO country(code, name) VALUES ('PY','Paraguay');
INSERT INTO country(code, name) VALUES ('PE','Peru');
INSERT INTO country(code, name) VALUES ('PH','Philippines');
INSERT INTO country(code, name) VALUES ('PO','Pitcairn Island');
INSERT INTO country(code, name) VALUES ('PL','Poland');
INSERT INTO country(code, name) VALUES ('PT','Portugal');
INSERT INTO country(code, name) VALUES ('PR','Puerto Rico');
INSERT INTO country(code, name) VALUES ('QA','Qatar');
INSERT INTO country(code, name) VALUES ('ME','Montenegro, Republic of');
INSERT INTO country(code, name) VALUES ('RS','Serbia, Republic of');
INSERT INTO country(code, name) VALUES ('RE','Reunion');
INSERT INTO country(code, name) VALUES ('RO','Romania');
INSERT INTO country(code, name) VALUES ('RU','Russia');
INSERT INTO country(code, name) VALUES ('RW','Rwanda');
INSERT INTO country(code, name) VALUES ('NT','St. Barthelemy');
INSERT INTO country(code, name) VALUES ('EU','St. Eustatius');
INSERT INTO country(code, name) VALUES ('HE','St. Helena');
INSERT INTO country(code, name) VALUES ('KN','St. Kitts-Nevis');
INSERT INTO country(code, name) VALUES ('LC','St. Lucia');
INSERT INTO country(code, name) VALUES ('MB','St. Maarten');
INSERT INTO country(code, name) VALUES ('PM','St. Pierre & Miquelon');
INSERT INTO country(code, name) VALUES ('VC','St. Vincent & Grenadines');
INSERT INTO country(code, name) VALUES ('SP','Saipan');
INSERT INTO country(code, name) VALUES ('SO','Samoa');
INSERT INTO country(code, name) VALUES ('SM','San Marino');
INSERT INTO country(code, name) VALUES ('ST','Sao Tome & Principe');
INSERT INTO country(code, name) VALUES ('SA','Saudi Arabia');
INSERT INTO country(code, name) VALUES ('SN','Senegal');
INSERT INTO country(code, name) VALUES ('SC','Seychelles');
INSERT INTO country(code, name) VALUES ('SL','Sierra Leone');
INSERT INTO country(code, name) VALUES ('SG','Singapore');
INSERT INTO country(code, name) VALUES ('SK','Slovakia');
INSERT INTO country(code, name) VALUES ('SI','Slovenia');
INSERT INTO country(code, name) VALUES ('SB','Solomon Islands');
INSERT INTO country(code, name) VALUES ('OI','Somalia');
INSERT INTO country(code, name) VALUES ('ZA','South Africa');
INSERT INTO country(code, name) VALUES ('ES','Spain');
INSERT INTO country(code, name) VALUES ('LK','Sri Lanka');
INSERT INTO country(code, name) VALUES ('SD','Sudan');
INSERT INTO country(code, name) VALUES ('SR','Suriname');
INSERT INTO country(code, name) VALUES ('SZ','Swaziland');
INSERT INTO country(code, name) VALUES ('SE','Sweden');
INSERT INTO country(code, name) VALUES ('CH','Switzerland');
INSERT INTO country(code, name) VALUES ('SY','Syria');
INSERT INTO country(code, name) VALUES ('TA','Tahiti');
INSERT INTO country(code, name) VALUES ('TW','Taiwan');
INSERT INTO country(code, name) VALUES ('TJ','Tajikistan');
INSERT INTO country(code, name) VALUES ('TZ','Tanzania');
INSERT INTO country(code, name) VALUES ('TH','Thailand');
INSERT INTO country(code, name) VALUES ('TG','Togo');
INSERT INTO country(code, name) VALUES ('TK','Tokelau');
INSERT INTO country(code, name) VALUES ('TO','Tonga');
INSERT INTO country(code, name) VALUES ('TT','Trinidad & Tobago');
INSERT INTO country(code, name) VALUES ('TN','Tunisia');
INSERT INTO country(code, name) VALUES ('TR','Turkey');
INSERT INTO country(code, name) VALUES ('TU','Turkmenistan');
INSERT INTO country(code, name) VALUES ('TC','Turks & Caicos Is');
INSERT INTO country(code, name) VALUES ('TV','Tuvalu');
INSERT INTO country(code, name) VALUES ('UG','Uganda');
INSERT INTO country(code, name) VALUES ('UA','Ukraine');
INSERT INTO country(code, name) VALUES ('AE','United Arab Emirates');
INSERT INTO country(code, name) VALUES ('GB','United Kingdom');
INSERT INTO country(code, name) VALUES ('US','United States of America');
INSERT INTO country(code, name) VALUES ('UY','Uruguay');
INSERT INTO country(code, name) VALUES ('UZ','Uzbekistan');
INSERT INTO country(code, name) VALUES ('VU','Vanuatu');
INSERT INTO country(code, name) VALUES ('VS','Vatican City State');
INSERT INTO country(code, name) VALUES ('VE','Venezuela');
INSERT INTO country(code, name) VALUES ('VN','Vietnam');
INSERT INTO country(code, name) VALUES ('VB','Virgin Islands (Brit)');
INSERT INTO country(code, name) VALUES ('VA','Virgin Islands (USA)');
INSERT INTO country(code, name) VALUES ('WK','Wake Island');
INSERT INTO country(code, name) VALUES ('WF','Wallis & Futana Is');
INSERT INTO country(code, name) VALUES ('YE','Yemen');
INSERT INTO country(code, name) VALUES ('ZR','Zaire');
INSERT INTO country(code, name) VALUES ('ZM','Zambia');
INSERT INTO country(code, name) VALUES ('ZW','Zimbabwe');
